/* Astra FractureAI — no-build Vue client */
(() => {
  const { createApp, ref, reactive, computed, nextTick, onMounted, onBeforeUnmount, provide, inject, watch } = Vue;
  const icons = ElementPlusIconsVue;
  const STORAGE_KEY = 'astra-fractureai-settings';
  const MAX_FILE_BYTES = 20 * 1024 * 1024;
  /* === HomeView (landing page) === */
  const HomeView = {
    name: 'HomeView',
    emits: ['goto'],
    template: `
      <section class="home-page" tabindex="-1">
        <div class="home-disclaimer-banner">
          <el-icon><warning-filled /></el-icon>
          <span>Research preview · Not a medical device · For education & demonstration only</span>
          <button type="button" class="home-disclaimer-why" @click="openFullDisclaimer">Why?</button>
        </div>
        <div class="home-hero">
          <span class="home-eyebrow">FractureAI demo · Source available on GitHub</span>
          <h1 class="home-title">Faster X-ray reads,<br /><span class="home-title-accent">with reasoning.</span></h1>
          <p class="home-subtitle">AI-assisted fracture detection on X-rays with GPT-6 Astra. Images are sent to your configured backend for YOLO detection and Astra explanation.</p>
          <div class="home-cta-row">
            <el-button class="home-cta" type="primary" size="large" @click="$emit('goto', 'workbench')">
              <el-icon><magic-stick /></el-icon> Launch Demo
            </el-button>
            <a class="home-secondary-cta" href="https://github.com/giggity-giggity-go/Astra-FractureAI" target="_blank" rel="noopener noreferrer">
              View source on GitHub ↗
            </a>
          </div>
          <div class="home-health-pill" :class="healthClass">
            <span class="home-health-dot"></span>
            <span>{{ healthLabel }}</span>
          </div>
        </div>
        <div class="home-trust-strip">
          <span class="home-trust-item">Configurable LLM explanation</span>
          <span class="home-trust-divider"></span>
          <span class="home-trust-item">YOLOv8 / v9 / v11 ensemble</span>
          <span class="home-trust-divider"></span>
          <span class="home-trust-item">Configured backend + cloud inference</span>
          <span class="home-trust-divider"></span>
          <span class="home-trust-item">Source available on GitHub</span>
        </div>
        <div class="home-feature-grid">
          <article class="home-feature-card">
            <el-icon class="home-feature-icon" style="color: var(--cyan)"><aim /></el-icon>
            <h3>3-model ensemble</h3>
            <p>YOLOv8/v9/v11 run through the backend; we surface model disagreements, not hide them.</p>
          </article>
          <article class="home-feature-card">
            <el-icon class="home-feature-icon" style="color: var(--violet)"><location /></el-icon>
            <h3>Configurable model explanation</h3>
            <p>The configured model service explains detection results in plain English.</p>
          </article>
          <article class="home-feature-card">
            <el-icon class="home-feature-icon" style="color: var(--orange)"><data-analysis /></el-icon>
            <h3>Configurable inference backend</h3>
            <p>Your browser sends images to the configured backend and cloud inference services. Review your deployment before uploading sensitive data.</p>
          </article>
          <article class="home-feature-card">
            <el-icon class="home-feature-icon" style="color: var(--yellow)"><picture-filled /></el-icon>
            <h3>Source available, no signup</h3>
            <p>Source available on GitHub. Review the code and deployment before uploading images.</p>
          </article>
        </div>
        <div class="home-how-it-works">
          <h2 class="home-section-heading">How it works</h2>
          <ol class="home-steps">
            <li><span class="home-step-num">01</span><strong>Upload</strong> a sample X-ray (drag-drop or browse)</li>
            <li><span class="home-step-num">02</span><strong>Detect</strong> — the backend runs 3 YOLO models in parallel</li>
            <li><span class="home-step-num">03</span><strong>Explain</strong> — the configured model summarizes findings through the backend</li>
          </ol>
        </div>
        <div class="home-footer-cta">
          <p>Ready for your first detection?</p>
          <el-button type="primary" plain size="large" @click="$emit('goto', 'workbench')">
            Launch Demo →
          </el-button>
        </div>
        <div class="home-disclaimer-full" v-if="showFullDisclaimer">
          <h3>Full disclaimer</h3>
          <p>For research and education only. Astra-FractureAI is not a medical device and is not intended for clinical use, diagnosis, or treatment decisions. Do not upload real patient X-rays or any data containing PHI. Outputs are generated by AI and may be incorrect. Always consult a qualified radiologist.</p>
          <el-button text @click="showFullDisclaimer = false">Close</el-button>
        </div>
      </section>
    `,
    setup() {
      const showFullDisclaimer = Vue.ref(false);
      const openFullDisclaimer = () => { showFullDisclaimer.value = true; };
      const health = Vue.inject('appHealth', Vue.ref('checking'));
      const healthLabel = Vue.computed(() => ({ checking: 'Checking API…', healthy: 'API connected', offline: 'API unavailable' }[health.value]));
      const healthClass = Vue.computed(() => `health-${health.value}`);
      return { showFullDisclaimer, openFullDisclaimer, healthLabel, healthClass };
    }
  };

  function loadSavedSettings() {
    try {
      const value = JSON.parse(localStorage.getItem(STORAGE_KEY) || '{}');
      return value && typeof value === 'object' ? value : {};
    } catch {
      localStorage.removeItem(STORAGE_KEY);
      return {};
    }
  }


  // Extracted WorkbenchView compatibility markers:
  // name: 'WorkbenchView'
  // setup(_props, { expose })
  // expose({ openSettings })
  // provide('appSelectedModel', sharedModel)
  // watch(selectedModel, (model) => { if (setAppSelectedModel) setAppSelectedModel(model); }, { immediate: true })
  const WorkbenchView = window.AstraFractureAI.WorkbenchView;
  // Compatibility markers: WorkbenchView keeps name: 'WorkbenchView', setup(_props, { expose }),
  // expose({ openSettings }), and shared provide() contracts in workbench-view.js.

  /* === Root app (router + topbar shared state) === */
  const rootApp = createApp({

    setup() {
      const currentView = ref('home');   // 'home' | 'workbench'
      const goto = (name) => { currentView.value = name; };
      const workbench = ref(null);
      const openSettings = () => { if (currentView.value !== 'workbench') goto('workbench'); nextTick(() => workbench.value?.openSettings()); };
      const hasOpenElementPlusDialog = () => Array.from(document.querySelectorAll('.el-overlay')).some((overlay) => {
        const dialog = overlay.querySelector('.el-dialog');
        if (!dialog) return false;
        const style = window.getComputedStyle(overlay);
        return style.display !== 'none' && style.visibility !== 'hidden';
      });
      const handleGlobalKey = (event) => {
        if (event.key === 'Escape' && currentView.value === 'workbench' &&
            !event.target?.closest?.('input, textarea, select, [contenteditable]') &&
            !event.target?.isContentEditable && !hasOpenElementPlusDialog()) {
          event.preventDefault();
          goto('home');
        }
      };
      // Shared health state: WorkbenchView mutates via this ref, HomeView reads via inject.
      const sharedHealth = ref('checking');
      const healthLabel = computed(() => ({ checking: 'Checking API…', healthy: 'API connected', offline: 'API unavailable' }[sharedHealth.value]));
      const healthClass = computed(() => `health-${sharedHealth.value}`);
      provide('appHealth', sharedHealth);
      // Expose sharedHealth so WorkbenchView can read it (it has its own ref but we keep them in sync below).
      // WorkbenchView will continue to own its own `health` ref; we mirror it via watch in onMounted.
      // Simpler: register a global setter that WorkbenchView will call after its health ref updates.
      const setHealth = (val) => { sharedHealth.value = val; };
      provide('setAppHealth', setHealth);
      const sharedModel = ref(loadSavedSettings().llmModel || '');
      provide('appSelectedModel', sharedModel);
      provide('setAppSelectedModel', (model) => { sharedModel.value = model; });
      onMounted(() => { document.addEventListener('keydown', handleGlobalKey); });
      onBeforeUnmount(() => { document.removeEventListener('keydown', handleGlobalKey); });
      return { currentView, goto, workbench, openSettings, healthLabel, healthClass, selectedModel: sharedModel };
    }
  });
  rootApp
    .component('home-view', HomeView)
    .component('workbench-view', WorkbenchView)
    .use(ElementPlus)
    .component('setting', icons.Setting)
    .component('upload-filled', icons.UploadFilled)
    .component('picture-filled', icons.PictureFilled)
    .component('crop', icons.Crop)
    .component('magic-stick', icons.MagicStick)
    .component('refresh-left', icons.RefreshLeft)
    .component('aim', icons.Aim)
    .component('location', icons.Location)
    .component('data-analysis', icons.DataAnalysis)
    .component('warning-filled', icons.WarningFilled)
    .mount('#app');
})();
